version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: "cypress/included:3.2.0"
        
    steps:
      - checkout
      - run: echo "this is the build job"
 - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # we need to install CircleCI CLI tool
      # to run the "manual" tests
      - circleci-cli/install
      - run: npm test
      - run: npm run manual:tests
      - run: npm run docs


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
